In [30]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
print(y)
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
#Training get the weights of the network
for j in range(6000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
    
    
#Test the network we have trained  
test_X=np.array([[1,0,1]])
l1 = 1/(1+np.exp(-(np.dot(test_X,syn0))))
l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
print(l2)

[[0]
 [1]
 [1]
 [0]]
[[ 0.9870922]]


In [31]:
syn0

array([[-4.26538781,  0.17781653, -3.45950994, -6.68309067],
       [-4.04117938,  1.23860479, -3.00065391, -6.77326905],
       [ 6.12126459,  1.28949972,  4.69997258,  2.82949599]])

In [32]:
syn1

array([[  6.68848931],
       [ -5.68219274],
       [  4.39466472],
       [-11.48417421]])

In [27]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)

#Test the network we have trained 
test_X=np.array([[1,0,1]])
l1 = nonlin(np.dot(test_X,syn0))
print (l1)

Output After Training:
[[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]
[[ 0.99358931]]
