In [3]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
alpha,hidden_dim,dropout_percent,do_dropout = (0.5,4,0.2,True)
synapse_0 = 2*np.random.random((3,hidden_dim)) - 1
synapse_1 = 2*np.random.random((hidden_dim,1)) - 1
for j in range(60000):
    layer_1 = (1/(1+np.exp(-(np.dot(X,synapse_0)))))
    if(do_dropout):
        layer_1 *= np.random.binomial([np.ones((len(X),hidden_dim))],1-dropout_percent)[0] * (1.0/(1-dropout_percent))
    layer_2 = 1/(1+np.exp(-(np.dot(layer_1,synapse_1))))
    layer_2_delta = (layer_2 - y)*(layer_2*(1-layer_2))
    layer_1_delta = layer_2_delta.dot(synapse_1.T) * (layer_1 * (1-layer_1))
    synapse_1 -= (alpha * layer_1.T.dot(layer_2_delta))
    synapse_0 -= (alpha * X.T.dot(layer_1_delta))
print(synapse_0)
print(synapse_1)

[[-10.25909155 -10.29078587  -8.75441888 -65.88323255]
 [-42.45870026 -46.30650481  -9.21905109  88.24049142]
 [ 44.80173728  48.45062749   1.00654329   7.27366709]]
[[  4.10248935]
 [  4.22354269]
 [-15.80544119]
 [ -2.32565985]]


In [ ]:
Dropout helps prevent weights from converging to identical positions. 
It does this by randomly turning nodes off when forward propagating. 
It then back-propagates with all the nodes turned on. 